#!/bin/bash
# Stream a black screen with silence to YouTube Live
# Usage: liveblackscreen "YOUR_STREAM_KEY"

if [ -z "$1" ]; then
  echo "Usage: liveblackscreen <stream_key>"
  exit 1
fi

STREAM_KEY="$1"
RTMP_URL="rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY"

echo "Starting black screen stream to YouTube..."
echo "RTMP URL: rtmp://a.rtmp.youtube.com/live2/****"
echo "Press Ctrl+C to stop"
echo ""

ffmpeg -re \
       -f lavfi -i color=c=black:s=1280x720:r=30 \
       -f lavfi -i anullsrc=r=44100:cl=stereo \
       -c:v libx264 -preset ultrafast -tune zerolatency -g 60 -keyint_min 60 -b:v 2500k \
       -c:a aac -b:a 128k \
       -f flv "$RTMP_URL"
